### ISSUE TITLE
<Feature Request> Show ban reason

### ISSUE THREAD

**Issue by oitdmser** [Mirobit/bitcoin-node-manager#10]
`bitcoin-cli listbanned` returns a ban_reason value. It would be helpful if this was displayed in Bitcoin Node Manager's Ban List page under 'reason'. In my Reason list all I see is 'Core' which isn't helpful from a diagnostics standpoint.

**Comment by Mirobit** [comment]
`ban_reason` has only two values: `node misbehaving` and `manually added`. It is not more informative than the current `Core` / `User`.
A ban is based on the ban score, which can consist of many minor infractions. In most cases there isn't a single reason why a node was banned.
