### ISSUE TITLE
<Feature Request> show country and node  type in Banlist

### ISSUE THREAD

**Issue by oitdmser** [Mirobit/bitcoin-node-manager#11]
It would be interesting to have a column in the ban list showing country of each banned IP. It would be something a person could see if  nodes in a certain country were misbehaving more frequently than others. Not a necessary feature, but interesting nonetheless

would it be possible to list client type in the banlist too? This would help visualize if bans were going to specific client or version

**Comment by Mirobit** [comment]
I will think about the country information. Since the bitcoind rpc call doesn't return the client of the banned peer, it is impossible to know. In some cases BNM might know about the peers client, but this would require that the users frequently visits BNM.

**Comment by photis** [comment]
Fwiw, I'd like to second this feature request.
