### ISSUE TITLE
Bitcoin Node Manager reports negative fees after halvening

### ISSUE THREAD

**Issue by drkskwlkr** [Mirobit/bitcoin-node-manager#12]
![image](https://user-images.githubusercontent.com/6951698/81607743-d80ce280-93dd-11ea-90e2-a6a6874e0310.png)

The pic says everything I can. Noticed it first on v0.3.0, updated to v0.5.0, confirmed.
My Bitcoin Core node runs version `0.18.0` with `Network`, `Bloom`, `Witness` and `Network Limited`.

**Comment by drkskwlkr** [comment]
I think I found the problem. Hard-coded value for block reward in src/Content.php, Line 150 and 152

https://github.com/Mirobit/bitcoin-node-manager/blob/ad35d4eafcbff53f5f8503df9019bf06d598a10c/src/Content.php#L150

https://github.com/Mirobit/bitcoin-node-manager/blob/ad35d4eafcbff53f5f8503df9019bf06d598a10c/src/Content.php#L152

**Comment by drkskwlkr** [comment]
Proposed fix in PR https://github.com/Mirobit/bitcoin-node-manager/pull/13

**Comment by Mirobit** [comment]
Thanks for reporting this and providing a smart solution. I merged the your pull request.
