### ISSUE TITLE
"Undefined index" ....

### ISSUE THREAD

**Issue by oitdmser** [Mirobit/bitcoin-node-manager#14]
When loading BNM the first time or refreshing after a long time of no viewing I often get 3-6 of the following errors. Waiting 30 seconds or so and refreshing makes them all go away.

<img width="892" alt="Screen Shot 2020-05-15 at 7 30 32 AM" src="https://user-images.githubusercontent.com/44953598/82061865-1d4f3f80-967e-11ea-9ff8-0c1df3aab823.png">

It seems like the page loads before the RPC portion gets all its data. These only rarely if ever appeared in v0.4.0. Is there some timeout value that changed from 0.4-0.5, or maybe some race condition?

**Comment by Mirobit** [comment]
Thanks for reporting this. I change the error reporting settings in 0.5. Starting 0.5 also displays notices. I assume that these bugs have always been there, but are now only visible.

I will look into this.

**Comment by oitdmser** [comment]
Appears to be fixed, at least for me, as of v0.6.0

**Comment by oitdmser** [comment]
I guess I spoke too soon. It pops up much less frequently (or maybe it's just my imagination?) as of v0.6.0, but does still happen, particularly after a daemon reboot.

**Comment by Mirobit** [comment]
I hope i finally fixed this bug (0f72f30fb0b76408108a8e864dc433f8c87c6b12).

**Comment by oitdmser** [comment]
Initial trials suggest it's fixed, thanks! I'll keep an eye out.

Thanks for all the hard work getting it to v1.0

**Comment by oitdmser** [comment]
Issue seems to be occurring again with both versions 1.0.0 and 1.1.0.


<img width="1433" alt="Screen Shot 2021-01-16 at 10 03 12 AM" src="https://user-images.githubusercontent.com/44953598/104819413-2af72f00-57e2-11eb-8032-209774363246.png">

**Comment by Mirobit** [comment]
This has beenb fixed since the last release. But I haven't put out an official release yet. Will do this tomorrow. Git pull should fix this as well.

**Comment by oitdmser** [comment]
Oooooohhh, I get it. Sorry, I assumed 1.0 and 1.1 included those changes. I did a `git pull https://github.com/Mirobit/bitcoin-node-manager.git master` and it works fine now

**Comment by Mirobit** [comment]
I was a little late with the release. Should have done it before the 0.21.0 release.

**Comment by oitdmser** [comment]
So it still does it occasionally, usually on the first refresh in a day or so. Any subsequent refreshes have zero errors. This time it's a different line, not sure if that's significant ...
<img width="749" alt="Screen Shot 2021-01-19 at 4 26 54 PM" src="https://user-images.githubusercontent.com/44953598/105110405-5ba1c780-5a73-11eb-956b-9e6e5dc6cad2.png">

**Comment by Mirobit** [comment]
Sadly it is still the same bug. I think happens if all previously known peers disconnected. I assume you have only outgoing peers?

**Comment by oitdmser** [comment]
No, on my nodes I have 90+ peers, mostly incoming

On Jan 19, 2021, at 5:17 PM, Michael Rotarius <notifications@github.com> wrote:

﻿
Sadly it is still the same bug. I think happens if all previously known peers disconnected. I assume you have only outgoing peers?

**Comment by Shanghai-maglev** [comment]
I have the same issue as of 26/02/2021.
- Always the same two "undefined error" lines
- Does not disappear 
- Using chrome browser

Apart from this minor bug, this software is awesome! Keep up the good work.

![image](https://user-images.githubusercontent.com/30261782/105768619-82a35080-5fc1-11eb-8b36-84d54a401e7d.png)

**Comment by Mirobit** [comment]
@Shanghai-maglev thanks for reporting this? What Bitcoin core version are you using and is the latest version of BNM installed?

**Comment by Shanghai-maglev** [comment]
> @Shanghai-maglev thanks for reporting this? What Bitcoin core version are you using and is the latest version of BNM installed?

Hi, I am on bitcoin core 0.21 and it appears I was using the outdated 1.10 BNM release. 

I have updated to the latest 1.20 and the issue appears to have gone away. Please note that when you download the .zip from GitHub directly, the file name for 1.20 is still set to "bitcoin-node-manager-1.1.0".

**Comment by pouyiouk** [comment]
All these errors result if bitcoind client is in the process of importing a new block header/block/sync a new block, considering that you already have a fully synced node. I have taken a good look at it, and when the node is busy writing to disk, rpc calls tend to become very heavy for bitcoind. Thus sometimes you might even get rpc timeout errors.

**Comment by Mirobit** [comment]
I think there are three different errors mixed up in this issue:
1. Whitelist error: Older BNM versions are not compatible with core 0.21.0. This is has been fixed.
2. Geo caching Error: In rare cases there is an issue with the geo caching. This is the oldest BNM bug and I thought I had it fixed a couple of times already. 
3. On some machines den rpc call fails under some conditions. This error should be caught by BNM and a error message ist shown (Not the php error/warning log). This is all I can do right now to fix this error.

**Comment by qertoip** [comment]
I do have the same issue. This only happens after re-visiting BNM after a while. Subsequent requests are fine.

**Comment by Mirobit** [comment]
This is really strange. I never encountered this issue. Could you delete `data/geodatapeers.inc`. Please let me know if the issues still appears after a few days.

**Comment by oitdmser** [comment]
> This is really strange. I never encountered this issue. Could you delete `data/geodatapeers.inc`. Please let me know if the issues still appears after a few days.

Deleting geodatapeers.inc fixes the problem immediately. I'll monitor it over time and let you know

**Comment by oitdmser** [comment]
After 24 hour wait, then refresh on a heavily connected (200+ peers) node I refreshed and get three lines of the same error. Another quick immediate refresh and the lines go away. Perhaps it's something to do with node that have disconnected?

**Comment by Mirobit** [comment]
I don't think it is the node that you disconnected. I rather think it is a peer that you are connected to, that I am not (e.g. two peers with the same IP, that could confusing the caching system?). I will have a closer look at the weekend.
