### ISSUE TITLE
Services not being reported correctly.

### ISSUE THREAD

**Issue by mcjoshea** [Mirobit/bitcoin-node-manager#15]
Hi, 

I've got a small issue with Bitcoin Node Manager and wondered if you would be able to help?

In the node information panel on the main screen, my node's services are reporting as unknown:

![node info](https://user-images.githubusercontent.com/63942949/85955135-8cee6500-b974-11ea-82f1-9ed75b158a47.JPG)

Yet when  I issue the command `bitcoin-cli getnetworkinfo` my node reports this:

![cli](https://user-images.githubusercontent.com/63942949/85955267-46e5d100-b975-11ea-99ac-6d3191cc99ee.JPG)

Bitnodes.io is also reporting my node's services correctly:

![bitnodes](https://user-images.githubusercontent.com/63942949/85955438-777a3a80-b976-11ea-9520-c68e7e2df2f2.JPG)

My set up is:
Raspberry Pi 3+
Raspberry Pi OS (Debian 10)
Apache 2.4.38
PHP 7.3
Bitcoin Core 0.20.0 (Snap Store)
Bitcoin Node Manager v0.6.0

My node is running in a standard home setup behind an ADSL router with port forwarding. The external IP address has been added to bitcoin.conf using `externalip=`

Any ideas?

**Comment by Mirobit** [comment]
Tanks for reporting this. Does the service detection work for your peers?

**Comment by mcjoshea** [comment]
Thanks for looking into this. Your update is working fine now for both for my own node and my peers.
