### ISSUE TITLE
Menu options missing on mobile devices.

### ISSUE THREAD

**Issue by mcjoshea** [Mirobit/bitcoin-node-manager#16]
Hi, 

Any chance of updating the mobile device support so menus are included?

This is how it looks on my Android phone:

![Screenshot](https://user-images.githubusercontent.com/63942949/85956158-e9a14e00-b97b-11ea-8b18-711a2a1e2e0b.jpg)

Would be great if the sidebar could be included as a drop down menu. At the moment there is no menu at all.

I get the same issues when I switch to the browser's desktop site option:

![android1](https://user-images.githubusercontent.com/63942949/85956406-a2b45800-b97d-11ea-843a-94dbafe8c9fc.jpg)

The screenshots are from Bromite but I get the same issue in Chrome. The phone is running Android 8.1.0. 

Thanks Mark

**Comment by Mirobit** [comment]
I never checked how the page looks on mobile devices. There is room for improvement. 
I don't do well with css, so I might take me a while to find a solution. I am open to suggestions.

**Comment by Mirobit** [comment]
I finally added a mobile menu (76ab46b). Let me know if it doesn't work for you.

**Comment by mcjoshea** [comment]
That's really good. Thanks!

Can you do anything with the layout on the main page? 

Something looks odd with the alignment of the top info panels:

![image](https://user-images.githubusercontent.com/63942949/102722183-54ae5a80-42f7-11eb-9aab-e7867c7164e0.png)
