### ISSUE TITLE
Errors in wallet section.

### ISSUE THREAD

**Issue by mcjoshea** [Mirobit/bitcoin-node-manager#17]
Hi,

I'm getting an error in the wallet section. Not sure if this is something to do with my setup. The chances are it is!

I have never used the wallet in my node and don't intend to. Just would just be nice not to get the error:

> Notice: Undefined index: utxo in /var/www/bitcoin/bnm/views/wallet.phtml on line 76
> Warning: Invalid argument supplied for foreach() in /var/www/bitcoin/bnm/views/wallet.phtml on line 76

![wallet error](https://user-images.githubusercontent.com/63942949/85956693-6681f700-b97f-11ea-8f44-5cf0c1d3aff0.JPG)

When I set up my node I included wallet support. I have not looked into this issue very much. I was hoping that it's something obvious that you've seen before.

I set up the node first on a PC using Bitcoin Core (64bit), downloaded the blockchain and then swapped the disk over to a Raspberry Pi, where it's running now. 

My setup is:
Raspberry Pi 3+
Raspberry Pi OS (Debian 10)
Apache 2.4.38
PHP 7.3
Bitcoin Core 0.20.0 (Snap Store)
Bitcoin Node Manager v0.6.0

The node is running with `txindex=1` in the config file.

Thanks
Mark

**Comment by Mirobit** [comment]
Thanks for reporting this. I didn't not check for the case that the wallet is active but doesn't have any transactions. This should be fixed (286e81c10a516648c4c22e92f86694eb951958cc).

**Comment by mcjoshea** [comment]
Thanks for looking into this. Your update is working fine now for both for my own node and my peers.
