### ISSUE TITLE
Peer filtering from main page

### ISSUE THREAD

**Issue by mcjoshea** [Mirobit/bitcoin-node-manager#18]
Would it be possible to link the main page to a filtered subset of connected peers when clicking the appropriate peer type or country?

For example, when clicking on any item in the top peer clients panel, say Core 0.20.0 peers for example, I'd like it to open up the Peers page and list all the Core 0.20.0 peers that are connected to my node. Same goes for the global peer distribution section. If I clicked on Germany for example, I'd like to see a list of all my German peers.

**Comment by Mirobit** [comment]
This is doable. I am putting this on my To-Do list.

**Comment by Mirobit** [comment]
I added the feature (53e0bc5). It doesn't work with long clients and `Other`. But for most clients and all countries it should work fine. Let me know if there is an issue with this feature.
