### ISSUE TITLE
Peer traffic information 

### ISSUE THREAD

**Issue by mcjoshea** [Mirobit/bitcoin-node-manager#19]
Could we have a way of seeing both uploaded and downloaded traffic for each individual peer on the peers page? Currently all we see is one traffic figure per peer. Something as simple as separate traffic in and traffic out columns would be great.

**Comment by Mirobit** [comment]
I have been think about some time about displaying more information about peers. I just not sure I can squeeze in another column. 
A tooltip/popover or a modal could be a solution.

**Comment by Mirobit** [comment]
You can now (93453d5) hover over the traffic of a peer to see more detailed traffic information. I am still thinking about separated rows, but than you need three rows.

**Comment by mcjoshea** [comment]
Thanks for adding it. Really useful to have. 

The change seems to have altered the cell formatting for me. Somehow the ISP column has shrunk so the row height has increased. 

New:

![image](https://user-images.githubusercontent.com/63942949/102704213-55e87480-4270-11eb-8515-94e395f2219b.png)

Old:

![image](https://user-images.githubusercontent.com/63942949/102704218-744e7000-4270-11eb-920a-6167619900ec.png)

I'm using Chrome Version 87.0.4280.88 (Official Build) (64-bit).
Zoom set to 100% for both
Resolution set as 1680 x 1050

Does it look the same for you?

**Comment by Mirobit** [comment]
I noticed the same but actually tried to fix that with the update. But on a smaller screen it did the opposite. Let me know if it is fixed now (ea9aae0).

**Comment by mcjoshea** [comment]
Looks good now.

![image](https://user-images.githubusercontent.com/63942949/102721632-e2884680-42f3-11eb-882d-a17a187d5f70.png)

Thanks.
