### ISSUE TITLE
Ban list reason error

### ISSUE THREAD

**Issue by mcjoshea** [Mirobit/bitcoin-node-manager#22]
After updating my node to Satoshi:0.20.1 I am now getting an error at the top of the page.

> Notice: Undefined index: ban_reason in /var/www/bitcoin/bnm/src/Content.php on line 72

The ban list for rules I have setup myself now shows the reason for my bans as "unknown"

![image](https://user-images.githubusercontent.com/63942949/93811436-0d58f500-fc48-11ea-9484-fd45a8e312ca.png)

If I clear out the ban list, the warning at the top of the screen goes away. 

I think this may be related to the recent update and the changes regarding misbehavnig peers. 

[https://bitcoin.org/en/release/v0.20.1#changes-regarding-misbehaving-peers](https://bitcoin.org/en/release/v0.20.1#changes-regarding-misbehaving-peers)

> There is no method to list discouraged addresses. They are not returned by the listbanned RPC. That RPC also no longer reports the ban_reason field, as "manually added" is the only remaining option.

**Comment by Mirobit** [comment]
Thanks for reporting and finding the change that caused the issue. I will fix this as soon as possible.

**Comment by Mirobit** [comment]
I removed all information regarding the ban reason. Since Bitcoin core got rid of the auto ban feature, the BNM ban feature is even more useful.
