### ISSUE TITLE
Bitcoin Block Explorer service on the Memory Pool page no longer works

### ISSUE THREAD

**Issue by mcjoshea** [Mirobit/bitcoin-node-manager#23]
When interrogating entries on the Memory Pool page, [Bitcoin Block Explorer](https://blockexplorer.com) no longer works. 

![image](https://user-images.githubusercontent.com/63942949/93812424-81e06380-fc49-11ea-82cf-68ad55af7ef2.png)

**Comment by Mirobit** [comment]
Thanks for reporting this. 5b50aad6416506e41c949ea73e3d3f6ce340be06 should fix it.
