### ISSUE TITLE
Bitcoin Block Explorer service on the Forks page no longer works

### ISSUE THREAD

**Issue by mcjoshea** [Mirobit/bitcoin-node-manager#24]
Thanks for fixing issue #23 

I was looking at the Forks page tonight and came across the same issue.

On this page there is only one option which does not work.

![image](https://user-images.githubusercontent.com/63942949/94087479-c4e73600-fe05-11ea-9fdc-13c0f0872c84.png)

It would be nice to give this page the same amount of options as the other pages.

Thanks

**Comment by mcjoshea** [comment]
Just realised that you may have already fix this when you fixed #23. I've not updated yet so if that's the case then just close this and I'll wait until you get #22 fixed before I update my server.

**Comment by Mirobit** [comment]
Thanks, I will look for a new one that supports forks. Most block explorers don't include forked blocks.

**Comment by Mirobit** [comment]
I added blockchair and blockchain.com. The support some forks. I couldn't find a block explorer that lists all forks.
