### ISSUE TITLE
Undefined index error.

### ISSUE THREAD

**Issue by mcjoshea** [Mirobit/bitcoin-node-manager#25]
This bug has been going on for a while but I have never had to forsite to take a screenshot of it until tonight.

![image](https://user-images.githubusercontent.com/63942949/94501993-022f3780-01fb-11eb-89e8-0d51eb4d7ab9.png)

I'm only interested in the top three lines.  The bottom line has already been logged as #22.

If I do a refresh the errors go away and don't come back for a while. I only ever see them when I open the site up after being away from it for for a while.  

![image](https://user-images.githubusercontent.com/63942949/94502202-8f728c00-01fb-11eb-8c5f-14a9ccf6c208.png)

The last time I looked at my node was about a day ago. 

I do also get similar errors appearing if a peer with an unknown country IP address connects to my node but it soon catches up and the error vanishes.

I know it's something to do with the IP country code lookup.  Any ideas?

**Comment by Mirobit** [comment]
Thanks for reporting this. This has been going on for a while (#14). There is a bug in caching the geo data. I will try to fix this soon.

**Comment by Mirobit** [comment]
I hope i finally fixed this bug (0f72f30fb0b76408108a8e864dc433f8c87c6b12). Please let me know if this happens.
