### ISSUE TITLE
node manager crashes while syncing

### ISSUE THREAD

**Issue by gianlucamazza** [Mirobit/bitcoin-node-manager#26]
Hello,

I am giving a try to bitcoin-node-manager to manage my new full node.
Actually I am still syncing the node and the manager crashes.

Is it possible to catch the error and to the keep the dashboard up while syncing or am I doing something wrong?

Thank you!
 

`
Warning: fopen(http://...@0.0.0.0:8332/): failed to open stream: HTTP request failed! in /home/nexus/bitcoin-node-manager/src/jsonRPCClient.php on line 136

Notice: Undefined variable: content in /home/nexus/bitcoin-node-manager/index.php on line 82
`

**Comment by Mirobit** [comment]
Hello @gianlucamazza,
sadly it is currently not possible to use the node manger during the sync process. If you encounter any issues after syncing, please let me know.
