### ISSUE TITLE
Rules broken after update to v1.0.0

### ISSUE THREAD

**Issue by mcjoshea** [Mirobit/bitcoin-node-manager#28]
After I updated to the latest version I got this error when manually running my rules from the Run Rules button:

![image](https://user-images.githubusercontent.com/63942949/102291659-7eecca80-3f3b-11eb-9b7c-a0c722f74aba.png)

Got both old and new versions running in different folders. The the old version's rules are still working fine.

Cleared down my ban list and tried again but still the same.

**Comment by Mirobit** [comment]
Thanks for reporting this @mcjoshea. This was a major oversight on my part. 
805b5c7 fixes the bug.
