### ISSUE TITLE
 Geo tracing errors after node restart

### ISSUE THREAD

**Issue by mcjoshea** [Mirobit/bitcoin-node-manager#30]
I restarted my node today and noticed these errors:

![image](https://user-images.githubusercontent.com/63942949/102694336-43dae780-4218-11eb-86d7-c4b299b8a554.png)

A short while later I did a refresh and got this:

![image](https://user-images.githubusercontent.com/63942949/102694354-56edb780-4218-11eb-8d0e-015d73bbfb01.png)

As soon as the geo tracing picked up the first IP address the errors went away.

I had just updated BNM to the very latest version so not sure if that had anything to do with this.  I seem to remember seeing this before but did not mention it as it went away within minutes.

**Comment by Mirobit** [comment]
I hope that I finally fixed this (f940e45). Please let me know if the errors from the second screenshot are still happening.

**Comment by mcjoshea** [comment]
Not yet :-(

Sometimes it looks fixed but then when I do a refresh it comes back.

Remember that I have to stop and start the node for all this to happen. Never usually see it. The error only occurs up to the point when the geolocation request picks up the first node's location.

Where the there are more error lines than usual, that's when I manually refreshed the page, possibly a few times.  

Let me know if you would like me to follow a set of predefined steps to help with the fault finding. Not sure how useful it is with me just randomly pressing refresh!

![image](https://user-images.githubusercontent.com/63942949/102704514-5b47be00-4274-11eb-964e-700e74c457f2.png)

![image](https://user-images.githubusercontent.com/63942949/102704519-70245180-4274-11eb-94c4-fe9078eb1402.png)

![image](https://user-images.githubusercontent.com/63942949/102704539-ad88df00-4274-11eb-87a7-679b348ce21c.png)

![image](https://user-images.githubusercontent.com/63942949/102704550-d1e4bb80-4274-11eb-9db5-70ec953d3aba.png)

![image](https://user-images.githubusercontent.com/63942949/102704573-0fe1df80-4275-11eb-9e88-930eafdc6cb8.png)

**Comment by Mirobit** [comment]
Okay this is weird. This doesn't seem to be related to the geo tracing. The errors happen in a part of the code that only interacts with Bitcoin Core. It seems that Bitcoin Core didn't have some information for certain peers at the time of the request. If you refresh after a few seconds Core apparently is able to provide this information. But I can't explain why these errors stop as soon as the first geo call is made.

For now I am out of ideas, since I am not able to reproduce it. You could try to update to 0.20.1 but I don't think that is the issue.

**Comment by mcjoshea** [comment]
Thanks for trying. Not a big deal really as it goes away after a minute or two, and only occurs after if I restart the node.

Not sure if it makes any difference but my node is running as a Snap image (https://snapcraft.io/bitcoin-core) on a Raspberry Pi 3 Model B+ running Linux bitcoin-pi 5.4.72-v7+ #1356 SMP.

![image](https://user-images.githubusercontent.com/63942949/102721878-61ca4a00-42f5-11eb-83a0-70b872f92778.png)

**Comment by mcjoshea** [comment]
Just a quick update. I restarted my node again and got no error at all.

All I did was add a whitelist IP address to the node's config file and removed this: peerbloomfilters=1
