### ISSUE TITLE
Info panel formatting issues 

### ISSUE THREAD

**Issue by mcjoshea** [Mirobit/bitcoin-node-manager#31]
I've mentioned this before as part of other issues but thought it might be best to raise it independently of them, now that they have all been resolved.

The issue is with the way the info panel information boxes are formatted. The individual info boxes are not the same size so if the page is resized they do not line up evenly.
 
![image](https://user-images.githubusercontent.com/63942949/103373702-8b415d80-4acd-11eb-8676-d903d5dc58c0.png)

![image](https://user-images.githubusercontent.com/63942949/103373751-ae6c0d00-4acd-11eb-8f09-6391a35d90a1.png)

![image](https://user-images.githubusercontent.com/63942949/103373768-bb88fc00-4acd-11eb-8058-80eff2335f99.png)

The reason they do not line up is that the info boxes are not all the same height. 

In the example below some are 97 pixels high and others are 95 pixels high. 

95
![image](https://user-images.githubusercontent.com/63942949/103373833-ed9a5e00-4acd-11eb-9aed-d475b4f7e10e.png)

97
![image](https://user-images.githubusercontent.com/63942949/103373839-f0954e80-4acd-11eb-8e4f-41f4865fa0b2.png)

97
![image](https://user-images.githubusercontent.com/63942949/103373846-f428d580-4acd-11eb-9348-10b46bfb60db.png)

95
![image](https://user-images.githubusercontent.com/63942949/103373853-f7bc5c80-4acd-11eb-82bb-fe8d02ee0095.png)

95
![image](https://user-images.githubusercontent.com/63942949/103373857-fbe87a00-4acd-11eb-85bf-9c0ed280b403.png)

95
![image](https://user-images.githubusercontent.com/63942949/103373865-fee36a80-4acd-11eb-8abb-9c1854da44ff.png)

I think this has something to do with the addition of the second font used for the GB text.

![image](https://user-images.githubusercontent.com/63942949/103373958-34885380-4ace-11eb-878e-93653712df06.png)

![image](https://user-images.githubusercontent.com/63942949/103373963-381bda80-4ace-11eb-9d84-d56290a631db.png)

![image](https://user-images.githubusercontent.com/63942949/103373971-3eaa5200-4ace-11eb-9876-9d325f634f95.png)

![image](https://user-images.githubusercontent.com/63942949/103373975-41a54280-4ace-11eb-95f1-092ac05812e9.png)

If this could be fixed I think the info boxes would line up evenly making the page look so much better on a smaller screen.

**Comment by Mirobit** [comment]
Thanks for looking into this. You were exactly right. The smaller "GB" caused this. 
7571ecd fixes that.
