### ISSUE TITLE
Node info panel doesn't display Tor v3 address

### ISSUE THREAD

**Issue by oitdmser** [Mirobit/bitcoin-node-manager#34]
bitcoind v0.21.0 now supports Tor v3 addresses exclusively. After upgrading my daemon BNM no longer displays the server's Tor address in the Node info panel. Perhaps just an issue with the RegEx that extracts it from the RPC call?

<img width="359" alt="Screen Shot 2021-01-16 at 10 05 48 AM" src="https://user-images.githubusercontent.com/44953598/104819444-6b56ad00-57e2-11eb-833d-00a649273951.png">

**Comment by Mirobit** [comment]
Thanks for reporting this. You are right about the regex. I will fix this as soon as possible.

**Comment by Mirobit** [comment]
Since the new address is very long I decided to show the address version instead (v2 or v3). But you hover over it to see the address. Let me know if it works

**Comment by oitdmser** [comment]
I can confirm that works. Good work @Mirobit!
