### ISSUE TITLE
Whitelisting error after upgrading to 

### ISSUE THREAD

**Issue by mcjoshea** [Mirobit/bitcoin-node-manager#35]
After upgrading my node to 0.21.0 this error has appeared:

![image](https://user-images.githubusercontent.com/63942949/104819678-ec379800-5826-11eb-88e3-57d30d179f05.png)

I think it's something to do with this:

> The getpeerinfo RPC no longer returns the whitelisted field by default. This field will be fully removed in the next major release. It can be accessed with the configuration option -deprecatedrpc=getpeerinfo_whitelisted. However, it is recommended to instead use the permissions field to understand if specific privileges have been granted to the peer. (#19770)
https://bitcoincore.org/en/releases/0.21.0/

I tried starting my node with with `-deprecatedrpc=getpeerinfo_whitelisted` and also putting that in my config file but it made no difference.

**Comment by Mirobit** [comment]
Did you update to the latest BNM version? I haven't done a release yet but this has been fixed since the last release. Please let me know if this still exists.

**Comment by mcjoshea** [comment]
Just updated BNM and it's working fine now. Thanks.
