### ISSUE TITLE
Ban List Cron Job no longer working after upgrade

### ISSUE THREAD

**Issue by mcjoshea** [Mirobit/bitcoin-node-manager#36]
Just realised that the ban list cron job is no longer working. I can manually run the rules and that works fine. It's just the cron jobs no longer work. 

Here's the error I get when I enter the cron job into the browser manually:

`Fatal error: Uncaught ArgumentCountError: Too few arguments to function App\jsonRPCClient::__construct(), 1 passed in /var/www/bitcoin/bnm/index.php on line 31 and at least 2 expected in /var/www/bitcoin/bnm/src/jsonRPCClient.php:39 Stack trace: #0 /var/www/bitcoin/bnm/index.php(31): App\jsonRPCClient->__construct('http://bitcoin:...') #1 {main} thrown in /var/www/bitcoin/bnm/src/jsonRPCClient.php on line 39`

If I go back to the old version of BNM it work fine except I get the whitelist error but the job runs successfully and the appropriate nodes are blocked. 

Any ideas?

**Comment by Mirobit** [comment]
I changed the code that makes the bitcoin core rpc call and forgot to change the cronjob part. Should be easy to fix.

**Comment by mcjoshea** [comment]
Thanks. All working again now.
