### ISSUE TITLE
Incorrect use of getrawtransaction() on function createBlocksContent().

### ISSUE THREAD

**Issue by iker190** [Mirobit/bitcoin-node-manager#37]
Blocks tab fails because function [getrawtransaction()](https://bitcoincore.org/en/doc/0.20.0/rpc/rawtransactions/getrawtransaction/) is missing a third argument "blockhash". Without this argument it just looks in the mempool for the txid not in the block.

Changing the line 116 on Content.php should fix the issue:
`$coinbaseTx = $bitcoind->getrawtransaction($block["tx"][0], 1);` to 
`$coinbaseTx = $bitcoind->getrawtransaction($block["tx"][0], 1, $block["hash"]);`

Thank you for your work!

**Comment by Mirobit** [comment]
Thanks for the tip. This way BNM can get ride of the `txindex=1` requirement. Don't know why I didn't see this sooner.
Improved in 4397005.
