### ISSUE TITLE
Add NODE_COMPACT_FILTERS service flag support

### ISSUE THREAD

**Issue by qertoip** [Mirobit/bitcoin-node-manager#38]
For the connected Bitcoin node and for the peers it would be cool to support the new `NODE_COMPACT_FILTERS` service flag.

This regards "Services" paragraph and column.

PS Keep up the great work! I find BNM valuable tool.

**Comment by Mirobit** [comment]
BNM supports detecting NODE_COMPACT_FILTERS as of 1.2.0 (fcf1e2feea29b84dfcde0c79c8e3fdc4d9739cb3). I just think that there are only very few node that signal it yet.
