### ISSUE TITLE
Add option to disable password

### ISSUE THREAD

**Issue by qertoip** [Mirobit/bitcoin-node-manager#40]
In some scenarios like localhost setup or onion client auth the password becomes pointless and also hinders infrastructure tests automation.

It would be cool to add option to disable password authentication.

TIA!

**Comment by Mirobit** [comment]
Good idea. Thanks for providing the input. I added the option to BNM (7ed606b). Simply leave the password empty in the config file.

**Comment by qertoip** [comment]
Great, thanks. I hope you will cut a release soon :)
