### ISSUE TITLE
Tor address section does not display Tor address.

### ISSUE THREAD

**Issue by oitdmser** [Mirobit/bitcoin-node-manager#42]
Running v1.1.0, the new build that supports Tor v2 and v3 by displaying addresses on mouse-over. When I mouse-over the Tor address it incorrectly displays 127.0.0.1:9050 instead of the appropriate .onion address. If I run `bitcoin-cli getnetworkinfo` on the nodes the appropriate .onion address does appear in the 'localaddresses' section. 

<img width="274" alt="Screen Shot 2021-02-12 at 12 02 05 PM" src="https://user-images.githubusercontent.com/44953598/107816865-3464b000-6d2a-11eb-85e8-05e36e75ff7f.png">
<img width="310" alt="Screen Shot 2021-02-12 at 12 02 26 PM" src="https://user-images.githubusercontent.com/44953598/107816873-3595dd00-6d2a-11eb-80c0-217186a314ce.png">

**Comment by Mirobit** [comment]
Are you sure you are hovering over `v2` or `v3` and not the proxy icon? I improve the styling (1a5dbcb) to make it more obvious that the field is hoverable.

**Comment by oitdmser** [comment]
Whoops, you're right, I was hovering over the proxy icon.
