### ISSUE TITLE
Wrong blocknumber in header of index.php?p=blocks

### ISSUE THREAD

**Issue by photis** [Mirobit/bitcoin-node-manager#45]
The block number displayed in the header is wrong on this page (it is correct on other pages). It consistently displays the block number of the _first_ block in the 25-block range displayed, instead of the _last_ block. See attached image.

<img width="1367" alt="Screenshot 2021-05-03 at 07 38 34" src="https://user-images.githubusercontent.com/1708421/116841896-de8dfe80-abda-11eb-9507-073f639cf0e6.png">

**Comment by Mirobit** [comment]
Thanks for reporting this. Fixed in 83eb9efe40ba529b440bdf8743fee5db65215935.
