### ISSUE TITLE
Fatal error: Uncaught Exception: Unable to connect in /var/www/html/bnm/src/jsonRPCClient.php:144

### ISSUE THREAD

**Issue by SpanX** [Mirobit/bitcoin-node-manager#5]
I installed this on mu Odroid C1 with Ubuntu 18.04.4 LTS (GNU/Linux 3.10.107-13 armv7l)

So far it seems to work but when i click on "blocks" the following error comes:
`Fatal error: Uncaught Exception: Unable to connect in /var/www/html/bnm/src/jsonRPCClient.php:144 Stack trace: #0 /var/www/html/bnm/src/Content.php(149): App\jsonRPCClient->__call('getrawtransacti...', Array) #1 /var/www/html/bnm/index.php(342): App\createBlocksContent() #2 {main} thrown in /var/www/html/bnm/src/jsonRPCClient.php on line 144`

please help
![bnm](https://user-images.githubusercontent.com/6965242/76089088-610c3580-5fb9-11ea-9d11-c4dd7546700a.jpg)

And some informational lines (IPv4) don't work

**Comment by SpanX** [comment]
any updates?

**Comment by Mirobit** [comment]
@SpanX Thanks for reporting this. I have not been able to reproduce this issue. But I will have a closer look once I have some time available.

There is definitely an issue with the IP settings.

**Comment by Mirobit** [comment]
@SpanX did you set _txindex=1_ in your _bitcoin.conf_?
Can you run `bitcoin-cli getrawtransaction a35dd866eecc23f5ffe1a26215dd54c369e8b4a735799d5539d43fb62eef31c6 1` via your command line without getting an error?

**Comment by SpanX** [comment]
i didn't set txindex and you're right i get an error if i do that

**Comment by Mirobit** [comment]
@SpanX thanks for checking. I will add a line about the _bitcoin.conf_ to the install section.

**Comment by SpanX** [comment]
i'm testing now but i don't think that's the fix, i'll keep you posted

**Comment by SpanX** [comment]
same error?

Fatal error: Uncaught Exception: Unable to connect in /var/www/html/bnm2/src/jsonRPCClient.php:144 Stack trace: #0 /var/www/html/bnm2/src/Content.php(149): App\jsonRPCClient->__call('getrawtransacti...', Array) #1 /var/www/html/bnm2/index.php(342): App\createBlocksContent() #2 {main} thrown in /var/www/html/bnm2/src/jsonRPCClient.php on line 144

**Comment by Mirobit** [comment]
@SpanX is it working via the command line? Did you restart your _bitcoind_ with the _-reindex_ param?

**Comment by SpanX** [comment]
Reindex? No, doesn't that mean that I have to download everything all over
again?

**Comment by Mirobit** [comment]
@SpanX reindex doesn't not download any data. It just goes through all your block files und rebuildes the transaction database. It might take a while.

**Comment by SpanX** [comment]
Ok thanks, it's running on a raspberry pi clone.....takes forever

**Comment by Mirobit** [comment]
https://github.com/Mirobit/bitcoin-node-manager/issues/3#issuecomment-619632820 regarding the ipv4 issue. Everything should be working once your pi is done.
