### ISSUE TITLE
Feature request: Peers: indicate incoming or outgoing connection

### ISSUE THREAD

**Issue by proofer** [Mirobit/bitcoin-node-manager#51]
In my copy of Peer.php I have a new line after the initial assignment to $this->id
````
/bitcoin-node-manager/src$ diff Peer.php.orig Peer.php
44a45
>     $this->id = $peer["inbound"] ? '«' . $this->id : $this->id . '»';
````

**Comment by Mirobit** [comment]
Thanks for the input 👍🏻 . 
Add in dc74dbe0f7dfa9c7508756ca6f4189d9653f6eaa. I used a slightly different solution since I don't wanna clutter the id variable.
