### ISSUE TITLE
IPv4 is displayed incorrectly when multiple addresses are available

### ISSUE THREAD

**Issue by qertoip** [Mirobit/bitcoin-node-manager#53]
The expected behavior is to pick the IPv4 with the **highest score** value returned by `getnetworkinfo`.

It seems BNM currently simply picks random (or maybe the last) IPv4 on the list.

**Comment by Mirobit** [comment]
I think it was just using the last IP bitcoin core provided. This should be fixed now (d0a16c9b7c8453ff35a8a9b2a7dd72aa77cc6286).
Please let me know if it works. I don't have multiple ipv4 ips to test it.
