### ISSUE TITLE
Peers are not displayed if there is no password.

### ISSUE THREAD

**Issue by MontejoJorge** [Mirobit/bitcoin-node-manager#62]
If the password is deleted, the list of connected peers will not be displayed.

**Comment by MontejoJorge** [comment]
The problem is in this line, because if no password is set, the `csfrToken` field inside the session will not exist and will return an error.

https://github.com/Mirobit/bitcoin-node-manager/blob/4794b8bd02f7da7044b7629917c85881cb89b8a3/views/peers.phtml#L179

**Comment by Mirobit** [comment]
Fixed in #63
