### ISSUE TITLE
Deprecated Warnings and Compatibility Issues on PHP 8.2.8

### ISSUE THREAD

**Issue by k0gen** [Mirobit/bitcoin-node-manager#67]
When running BNM (bitcoin-node-manager) on PHP version 8.2.8, the following deprecated warnings and compatibility issues are observed:

    Deprecated: Creation of dynamic property App\Node::$services is deprecated in /var/www/bitcoin-node-manager/src/Node.php on line 120.

    Deprecated: Implicit conversion from float 1690900116.296 to int loses precision in /var/www/bitcoin-node-manager/src/Utility.php on line 226.

    Deprecated: Creation of dynamic property App\Node::$mempoolSize is deprecated in /var/www/bitcoin-node-manager/src/Node.php on line 132.

I'm running BNM from alpine:3.18 Docker container with `nginx` and `php82 php82-fpm php82-curl php82-session`

Main and Memory Pool tabs are affected 

Screenshot:

![Screenshot from 2023-08-01 16 43 12](https://github.com/Mirobit/bitcoin-node-manager/assets/3606313/c484f489-a263-42a9-bc7f-32e2b4c7eed7)

Please let me know if you need more information. Thank you for creating this wonderful piece of software!

**Comment by Mirobit** [comment]
Thanks for reporting this 👍🏻.
Fixed in [73595aa](https://github.com/Mirobit/bitcoin-node-manager/commit/73595aa8295f42126152f0e64d3352482031c5ab)
