### ISSUE TITLE
Add "Log Out" Feature for Current Session

### ISSUE THREAD

**Issue by k0gen** [Mirobit/bitcoin-node-manager#68]
Implement a "Log Out" feature that allows users to securely log out from their current session in Bitcoin Node Manager. This feature will enhance the user experience and improve security by terminating the active session and requiring re-authentication upon the next login.

**Comment by Mirobit** [comment]
That is indeed a useful feature 👍🏻 . I added in [38f4c35](https://github.com/Mirobit/bitcoin-node-manager/commit/38f4c3585568e907db6c519a257619ea4fcb01b5).
