### ISSUE TITLE
v0.5.0 divide by zero error when no banned nodes

### ISSUE THREAD

**Issue by oitdmser** [Mirobit/bitcoin-node-manager#7]
Running v0.5.0 on a node that currently has zero banned nodes and I get the following error at the top of the page:
<img width="671" alt="Screen Shot 2020-05-01 at 7 54 10 PM" src="https://user-images.githubusercontent.com/44953598/80853423-a75ec900-8be5-11ea-90e3-4d20cf145204.png">

**Comment by Mirobit** [comment]
@oitdmser Thaks for bringing this to my attention. I never had an empty ban list ;)
a2713c917d9f377e9494208694ae32d363f54703 should fix this

**Comment by oitdmser** [comment]
That fixed it. Much appreciated. I've noticed TOR-only nodes often have zero banned users
