### ISSUE TITLE
Suggestion: Relocate Memory Pool Metrics and Remove Memory Pool Transactions Tab

### ISSUE THREAD

**Issue by k0gen** [Mirobit/bitcoin-node-manager#70]
The "Memory Pool Transactions" tab in Bitcoin Node Manager is currently disabled due to memory concerns. To improve the user experience and resource management, I suggest making the following changes:

1. Unifi the "TX in Mempool" and "Usage" metrics on the "Main" tab for easy access and monitoring .
2. Remove the "Memory Pool" tab.

**Benefits:**
- Streamlined user interface with essential memory pool metrics readily available on the main page.
- Enhanced user experience without the need to access a separate tab for mempool metrics.

**Future Considerations:**
In the long term, as the application evolves, the "Memory Pool Transactions" tab could potentially be re-implemented with memory usage optimizations.

**Comment by MontejoJorge** [comment]
I don't like the idea of add other stat to the home page main panel, but maybe in add it in the node card? or create other card with mempol stats such as usage and average fee per tx. [Here is all the result of getmempoolinfo method](https://developer.bitcoin.org/reference/rpc/getmempoolinfo.html).

**Comment by k0gen** [comment]
I have just noticed that "TX in Mempool" is actually there:
<img width="1452" alt="Screenshot 2023-08-05 at 05 15 03" src="https://github.com/Mirobit/bitcoin-node-manager/assets/3606313/51777dac-888d-4ccb-b17e-28d02fbb12fa">
What is really left in the "Moemory Pool" tab is just the Usage (reflected in MB)
<img width="1452" alt="Screenshot 2023-08-05 at 05 27 30" src="https://github.com/Mirobit/bitcoin-node-manager/assets/3606313/dfb4a825-16fa-44e5-a1c9-cc5b01d684ab">
I agree @MontejoJorge it might be a better idea to restructure the "Node" card to include Mempool usage in MB or make a separate Mempool card for stats.

**Comment by Mirobit** [comment]
True, the Memory pol is kind of pointless. It should be unified on the main page. A solution could be to show the usage in MB on only if you hover over the _xx% usage_. That way no extra space would be needed.

**Comment by k0gen** [comment]
> True, the Memory pool page is kind of pointless. It should be unified on the main page. A solution could be to show the usage in MB on only if you hover over the _xx% usage_. That way no extra space would be needed.

Excellent idea!
