### ISSUE TITLE
[Feature Request] Adding a Dark Theme

### ISSUE THREAD

**Issue by spyhuntergenral** [Mirobit/bitcoin-node-manager#76]
Adding a general dark theme to the web GUI would be pretty cool.

**Comment by Mirobit** [comment]
Thanks for the suggestion. Since the base theme doesn't have a dark theme (https://github.com/ColorlibHQ/gentelella/issues/835), someone needs to add the manually. Since I don't like CSS, someone needs to submit a pull request. I wouldn't have high hopes that this will happen.
