### ISSUE TITLE
v0.5.0 fopen http error

### ISSUE THREAD

**Issue by oitdmser** [Mirobit/bitcoin-node-manager#8]
Upgraded to v0.5.0. BNM displays all node status properly, but shows this error at the top. It seems to indicate BNM cannot connect to the node on localhost, but confusingly BNM is displaying appropriate node info. Not sure what is going on.

<img width="1440" alt="Screen Shot 2020-05-01 at 7 57 01 PM" src="https://user-images.githubusercontent.com/44953598/80853800-48e71a00-8be8-11ea-8476-6b1f47fab292.png">

**Comment by Mirobit** [comment]
This is strange. I can not reproduce this error. It seems that only one the bitcoin rpc calls fails. Are you sure than no information is missing? Is this only on the _Main_ page?

**Comment by oitdmser** [comment]
it is in fact only on the main page

**Comment by oitdmser** [comment]
I don't see any other error info. It's possible I'm doing something wrong here though. Any other information I can give you that would be helpful?

**Comment by oitdmser** [comment]
I noticed the error says `http://...@127.0.01:8332`. The "..." wasn't added by me, the error says that verbatim. Trying to connect to http://...@127.0.0.1:8332 would obviously fail. Is this perhaps the issue or does the code insert an ellipsis to simply obfuscate the RPC login/pw?

**Comment by Mirobit** [comment]
@oitdmser Your hunch with the wallet was right. There is no way to check if the wallet is activated, without making a RPC call that will fail if deactivated. That caused the warning message. 

With cd84e62986b3468e522ab4b7a27f71faaf12611e, wallet RPC calls are only made if your are on the wallet page. There is still a warning message, but only on the wallet page. So it shouldn't bother anyone. This is only quick fix.

> Trying to connect to http://...@127.0.0.1:8332 would obviously fail.
The username and password are not shown in error messages.

Thanks for bringing this bug to my attention.

**Comment by oitdmser** [comment]
That fixes it. Thanks!

**Comment by oitdmser** [comment]
> @oitdmser Your hunch with the wallet was right. There is no way to check if the wallet is activated, without making a RPC call that will fail if deactivated. That caused the warning message.
> 
> With [cd84e62](https://github.com/Mirobit/bitcoin-node-manager/commit/cd84e62986b3468e522ab4b7a27f71faaf12611e), wallet RPC calls are only made if your are on the wallet page. There is still a warning message, but only on the wallet page. So it shouldn't bother anyone. This is only quick fix.


It's likely I'm not the only one running with wallet disabled. You might consider making the Wallet tab a selectable option in Settings.
