### ISSUE TITLE
Invalid RPC credentials

### ISSUE THREAD

**Issue by kosuodhmwa** [Mirobit/bitcoin-node-manager#83]
**Config.php:**

 // RPC username / rpcauth specified in bitcoin.conf
    const RPC_USER = "myuser";
    // RPC password / rpcauth specified in bitcoin.conf
    const RPC_PASSWORD = "mypass";

**bitcoin.conf:**

proxy=127.0.0.1:9050
listen=1
bind=127.0.0.1

server = 1
   rpcallowip = 127.0.0.1
   rpcport = 8332
   rpcuser = myuser
   rpcpass = mypass
   txindex = 1
   
   
   PHP Version is 8.2.x

![image](https://github.com/Mirobit/bitcoin-node-manager/assets/24782840/e8a74806-cccf-4b40-8c88-438bfdc58545)

**Comment by kosuodhmwa** [comment]
this is really a bug, so the current version is "buggy by default" ?

**Comment by kosuodhmwa** [comment]
or do i need to change the PHP version to 7.3, not higher?

**Comment by kosuodhmwa** [comment]
???

**Comment by NDLcode** [comment]
If you run with docker add the following in your bitcoin.conf :

rpcallowip=172.0.0.0/8
rpcallowip=10.0.0.0/8
rpcallowip=192.0.0.0/

Try also to set Config.php RPC_IP to local server IP addr instead of 127.0.0.1

**Comment by kosuodhmwa** [comment]
Thanks, but i don't use docker

**Comment by MontejoJorge** [comment]
Then your rpc credentials are wrong, be sure that they are in bitcoin.conf. In the bitcoin logs you must see an invalid password attempt.

**Comment by kosuodhmwa** [comment]
no 
![image](https://github.com/Mirobit/bitcoin-node-manager/assets/24782840/950fe1e0-bdb5-4743-b8b5-39f4d2a1ada9)

**Comment by kosuodhmwa** [comment]
Still the same issue after 2 months with installed new versions. Why? 

![image](https://github.com/Mirobit/bitcoin-node-manager/assets/24782840/103d8e99-4531-4b74-9cd7-ec7113c79159)

**Comment by kosuodhmwa** [comment]
![image](https://github.com/Mirobit/bitcoin-node-manager/assets/24782840/69dd7560-157f-4414-880e-ac409623012d)

**Comment by kosuodhmwa** [comment]
![image](https://github.com/Mirobit/bitcoin-node-manager/assets/24782840/b23a3514-68a5-4ddd-8b79-3df5601653f9)

**Comment by kosuodhmwa** [comment]
![doomer](https://github.com/Mirobit/bitcoin-node-manager/assets/24782840/5d310f92-a3d5-4fbb-9621-0e7ce81f76d4)
This

**Comment by kosuodhmwa** [comment]
Maybe somebody knows a good alternative to https://github.com/Mirobit if they don't move up...?

THank you for your feedback(s) ;-)

**Comment by kosuodhmwa** [comment]
Additional info from bitcoind screens logs: 

PAssword is EXACTLY the same WTF (you see that in screenshots above)

![image](https://github.com/Mirobit/bitcoin-node-manager/assets/24782840/52b4d902-e95d-4312-ad1e-45c6ec021346)

**Comment by kosuodhmwa** [comment]
Maybe i need to put it in quotes in bitcoin.conf??

**Comment by MontejoJorge** [comment]
> ![image](https://private-user-images.githubusercontent.com/24782840/339768571-69dd7560-157f-4414-880e-ac409623012d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNzQ0MzgsIm5iZiI6MTcxODM3NDEzOCwicGF0aCI6Ii8yNDc4Mjg0MC8zMzk3Njg1NzEtNjlkZDc1NjAtMTU3Zi00NDE0LTg4MGUtYWM0MDk2MjMwMTJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDE0MDg1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3YzAyNDgxMTlmNTZlYjIxZmYwYjIzZTFjNzJjOGVlYTg3YmE2MjM2YTA5MDAwNzQ4Mzk0NGI0YWQwOTY5NTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UqvAtBGu5IFxrGAB_6L_cFAR7jnOc_jnmULxF2fmyg8)

Can you try it without spaces before and after the `=` ?

**Comment by kosuodhmwa** [comment]
Same... :-( 

![image](https://github.com/Mirobit/bitcoin-node-manager/assets/24782840/4025f940-168c-4eaa-b806-6d0c3b7bb921)
![image](https://github.com/Mirobit/bitcoin-node-manager/assets/24782840/c11c08f2-979d-454f-ad17-abb01849fb4d)
![image](https://github.com/Mirobit/bitcoin-node-manager/assets/24782840/cb38aef2-bce8-417c-8229-761f926fe24c)

<Btw i recomend to use rpcauth, not rpcuser and rpcpassword. https://jlopp.github.io/bitcoin-core-rpc-auth-generator/> - thx, but user/pw auth shoud also work. At least theoretically... ;-)

**Comment by kosuodhmwa** [comment]
i can also send the whole Oracle VirtualBox Debian 12.5 VM for debug purposes to @Mirobit if you want... it's not big when i subtract the .bitcoin data dir which contains the blockchain (.bitcoin is a symlink to another drive [than the OS drive] configured in VirtualBox VM settings)

**Comment by MontejoJorge** [comment]
Wait, i just realize why did u use `rpcpass`? its `rpcpassword`

**Comment by kosuodhmwa** [comment]
thank you very much. i also read about <rpcusername>... now i added both ones and restarted bitcoind - seems to work, :-)
