### ISSUE TITLE
Netherlands flag seems to be missing

### ISSUE THREAD

**Issue by kosuodhmwa** [Mirobit/bitcoin-node-manager#89]
![image](https://github.com/Mirobit/bitcoin-node-manager/assets/24782840/8a10d9ae-296b-4e44-91cd-40dd501de5ef)

**Comment by Barneyr73** [comment]
Got to assets/images/flags find Netherlands and rename it The Netherlands

**Comment by kosuodhmwa** [comment]
There is nothing in this directory... 
![image](https://github.com/Mirobit/bitcoin-node-manager/assets/24782840/3a51ff5a-c53b-49dc-8393-9483b00e98f1)

**Comment by kosuodhmwa** [comment]
Path was http://192.168.1.174/assets/images/flags/16/ - thx
