### ISSUE TITLE
Problem when i try to change (disable) Geo Tracing

### ISSUE THREAD

**Issue by kosuodhmwa** [Mirobit/bitcoin-node-manager#91]
![image](https://github.com/Mirobit/bitcoin-node-manager/assets/24782840/1994ae20-150d-4b98-ade0-612134630bdc)

**Comment by kosuodhmwa** [comment]
Do i need to change some directory permissions with chmod / chown?

**Comment by Mirobit** [comment]
The webserver needs write permissions for the data folder:
https://github.com/Mirobit/bitcoin-node-manager/blob/master/README.md

**Comment by kosuodhmwa** [comment]
There is nothing what exactly says what i have do to (chmod?): <Check that the server (e.g. www-data) has access (read and write) to the data folder (git will change the ownership by default)>

**Comment by kosuodhmwa** [comment]
???

**Comment by kosuodhmwa** [comment]
Maybe the question is too complex...?

**Comment by kosuodhmwa** [comment]
Hello?!?

**Comment by kosuodhmwa** [comment]
wtf
