### ISSUE TITLE
What means "Mempool limited" ? 

### ISSUE THREAD

**Issue by kosuodhmwa** [Mirobit/bitcoin-node-manager#92]
![image](https://github.com/Mirobit/bitcoin-node-manager/assets/24782840/e811f592-8227-4643-8ad6-bb534ac9ebeb)

**Comment by Mirobit** [comment]
The maximum size that you have set (or the default size (300 MB)) is smaller the current size of the total mempool. In that case Bitcoin Core starts removing transactions with the lowest fee rate from the mempool till it is smaller than your maximum size.

**Comment by kosuodhmwa** [comment]
Where can i set this?

**Comment by kosuodhmwa** [comment]
???

**Comment by kosuodhmwa** [comment]
hmm... https://github.com/bitcoin/bitcoin/issues/30539

**Comment by kosuodhmwa** [comment]
this: <You don't need to "handle" it at all. It's perfectly normal that your mempool drops transactions when it grows too large. You can configure the size of your mempool using the maxmempool setting> - https://github.com/bitcoin/bitcoin/issues/30539
