### ISSUE TITLE
sometimes it works, sometimes not

### ISSUE THREAD

**Issue by kosuodhmwa** [Mirobit/bitcoin-node-manager#94]
sometimes appears that message: Bitcoin Core not reachable: Operation timed out after 10003 milliseconds with 0 bytes received

why?

**Comment by MontejoJorge** [comment]
Sometimes the RPC server take more time to respond, you can edit the `CURLOPT_TIMEOUT` property in the `jsonRPCClient.php` file. Maybe we should add it to the `Config.php` file?

**Comment by kosuodhmwa** [comment]
thank you very much for your feedback.

<Maybe we should add it to the Config.php file?>

Yes, why not? :-)

**Comment by kosuodhmwa** [comment]
maybe a default value of 30 seconds would be better than only 10 (equivalent to the max_execution_timeout in php.ini...)

**Comment by kosuodhmwa** [comment]
solved, thx
